### PR TITLE
Fix tab's title on state change (fix ui router)

### LINKED ISSUE #892: Title doesn't change (bugged) (ui router upgrade)

### PR DESCRIPTION
**Pull request by ArsalanSavand**
Fixes #892 

Since I find out about that $stateChange... doesn't work in the new angularjs version, I used $transitions.

### CODE REVIEW

**Comment by ArsalanSavand** [comment]
I have fixed this issue, but we are still using $stateChange method which doesn't work anymore.
@Alir3z4 and @AmirSavand do you think we should use $transitions?

**Comment by Alir3z4** [comment]
I see.
@AmirSavand should be able to answer to your question

**Comment by AmirSavand** [comment]
It's because of new version of UI router, check this: https://stackoverflow.com/questions/37163811/angular-js-ui-router-statechangesuccess-event-not-firing

**Comment by AmirSavand** [comment]
We were using `"angular-ui-router": "^0.4.2",` in our `bower.json` and now that we use `npm` we also upgraded this which was a mistake, the entire usage of router has changed and other stuff we're not fully aware off.

@ArsalanSavand just downgrade to the version we were using before migrating to `npm`/`webpack` and revert your current changes :wink:

**Comment by AmirSavand** [comment]
We currently have other stuff to do and we have no problems with the older ui router, but if we want to migrate later, we should use this migration guide: https://ui-router.github.io/guide/ng1/migrate-to-1_0

**Comment by Alir3z4** [comment]
I thought this a bug right now that we're dealing with.

@ArsalanSavand if it's working for now, let it be until we upgrade its package.
For now as @AmirSavand said, let's continue stabbing on what we have.

**Comment by Alir3z4** [comment]
Another note, good that we didn't deploy the changes to production.
I blame this on the test coverage here.

Please get this fixed and have it in our shiny master branch.

**Comment by AmirSavand** [comment]
Seems like downgrading doesn't fix it.

Need to migrate...

**Comment by Alir3z4** [comment]
Migrating to Ruby on Rails :d

**Comment by AmirSavand** [comment]
@Alir3z4 is changelog for public or for us or for both?

**Comment by Alir3z4** [comment]
It's public on the repo.
Why would be private ?

**Comment by Alir3z4** [comment]
This looks good.
I also updated the changelog for better syntax and working.
Once CI passes, I'll merge

Thanks @ArsalanSavand <3

**Pull request merged**
