### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by Alir3z4**

### CODE REVIEW

**Comment by AmirSavand** [comment]
@Alir3z4 I pulled master into this branch, the build should succeed now and I'll merge once done.

**Comment by Alir3z4** [comment]
It doesn't need to pass.
It's just adding a file.

Anyway, merge once it's ready ;)

**Comment by Alir3z4** [comment]
ok, it passed.
I'm merging it.

**Comment by AmirSavand** [comment]
Nice

**Pull request merged**
