### PR TITLE
Add restore cache and working directory variable

### PR DESCRIPTION
**Pull request by Momjo**
- use executors

### CODE REVIEW

**Comment by AmirSavand** [comment]
What's up with this?

**Comment by Momjo** [comment]
> What's up with this?

already it's ready to merge 🤗

**Comment by AmirSavand** [comment]
@Alir3z4 please review this and approve.

@Momjo you haven't done my change request: https://github.com/SavandBros/gonevis-dash/pull/1110#pullrequestreview-199352346

**Comment by Alir3z4** [comment]
Wohooo!

This is merged now.
Thanks!

**Pull request merged**
