### PR TITLE
Footer text

### LINKED ISSUE #841: Website Settings: Custom footer text
User should be able to enter a custom footer text that will be shown on their website footer.

The field key on the serializer is `footer_text`.

### LINKED ISSUE #845: Update to AngularJS 1.7.0

### LINKED ISSUE #846: Update bower packages

### PR DESCRIPTION
**Pull request by AmirSavand**
Resolves #841
Resolves #845 
Resolves #846 

image

### CODE REVIEW

**Comment by Alir3z4** [comment]
The tests are failing https://circleci.com/gh/SavandBros/gonevis-dash/847
and the build on heroku failed as well with the below error:
```
    Running "ngAnnotate:dist" (ngAnnotate) task
       >> 2 files successfully annotated.
       
       Running "copy:dist" (copy) task
       Copied 15 files
       grunt[407]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
       1: node::Abort() [grunt]
       2: 0x876c55 [grunt]
       3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [grunt]
       4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [grunt]
       5: 0xacd2df [grunt]
       6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [grunt]
       7: 0x333cf518427d
       Aborted
       npm ERR! code ELIFECYCLE
       npm ERR! errno 134
       npm ERR! gonevisdash@1.0.0 postinstall: `npm install -g bower grunt-cli && bower install && grunt rock`
       npm ERR! Exit status 134
       npm ERR!
       npm ERR! Failed at the gonevisdash@1.0.0 postinstall script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.2hmit/_logs/2018-05-17T11_03_25_987Z-debug.log
-----> Build failed
```
There's an open issue at https://github.com/userfrosting/UserFrosting/issues/882

**Comment by Alir3z4** [comment]
I think you need to update the dependencies of the nodejs here in the packages.json.

**Comment by Alir3z4** [comment]
Heroku passed now
But the CI is still failing,I think it could be due to:
```
Please note that,
    angular-preload-image#5970a70176 depends on angular#~1.3.10 which resolved to angular#1.3.20
    angular-modal-service#0.13.0 depends on angular#1.5.0 - 1.6.x which resolved to angular#1.6.10
    angular-animate#1.7.0, angular-aria#1.7.0, angular-cookies#1.7.0, angular-messages#1.7.0, angular-mocks#1.7.0, angular-resource#1.7.0, angular-sanitize#1.7.0 depends on angular#1.7.0 which resolved to angular#1.7.0
    angular-medium-editor#1.2.1, ng-tags-input#3.2.0 depends on angular#>=1.3.0 which resolved to angular#1.7.0
    gonevis-dash depends on angular#^1.6.10 which resolved to angular#1.7.0
    angular-ui-router#0.4.2 depends on angular#^1.0.8 which resolved to angular#1.7.0
    angular-slugify#1.0.1 depends on angular#^1.0.x which resolved to angular#1.7.0
    angular-bootstrap#2.5.0 depends on angular#>=1.4.0 which resolved to angular#1.7.0
    ng-file-upload#12.2.13 depends on angular#>1.2.0 which resolved to angular#1.7.0
    angular-xeditable#0.8.1 depends on angular#~1.x which resolved to angular#1.7.0
    angular-chart.js#1.1.1 depends on angular#1.x which resolved to angular#1.7.0
    AngularJS-Toaster#2.2.0 depends on angular#>1.2.6 which resolved to angular#1.7.0
    angular-loading-bar#0.9.0 depends on angular#^1.2.9 which resolved to angular#1.7.0
    angular-gettext#2.3.11 depends on angular#>=1.2.0 which resolved to angular#1.7.0
    angular-local-storage#0.7.1 depends on angular#^1.x which resolved to angular#1.7.0
Resort to using angular#^1.6.10 which resolved to angular#1.6.10
Code incompatibilities may occur.
```

**Comment by AmirSavand** [comment]
@Alir3z4 that's just a warning about code incompatibilities is that a fatal error?

**Comment by Alir3z4** [comment]
@AmirSavand it might be why the tests are failing.
The build succeed but the tests don't.

**Comment by AmirSavand** [comment]
@Alir3z4 ready to merge! :+1:

**Comment by Alir3z4** [comment]
Okeit!

**Pull request merged**
