### PR TITLE
Release Tour

### PR DESCRIPTION
**Pull request by AmirSavand**
@Alir3z4 This is ready when backend is in production.

So merge it if backend has tour.

### CODE REVIEW

**Comment by AmirSavand** [comment]
@Alir3z4 bump.

**Comment by AmirSavand** [comment]
@Alir3z4 bump.

**Comment by Alir3z4** [comment]
Looking at it

**Comment by Alir3z4** [comment]
Backend is there, merging

**Comment by Alir3z4** [comment]
Excellent job @AmirSavand & @ArsalanSavand

**Pull request merged**
