### PR TITLE
Use npm

### PR DESCRIPTION
**Pull request by AmirSavand**
Dashboard comes up nicely but has issues.

- Tests fail
- Some packages have undefined errors in them
- Grunt needs to be configured (I just renamed bower_components to node_modules)

### CODE REVIEW

**Comment by Alir3z4** [comment]
There's no auto wire in this?
Like adding new package will not have its assets in the index.html

**Comment by AmirSavand** [comment]
No that's not the issue, it's actually better, some packages need to be ordered carefully. Like bootstrap and fontawesome that we configured for bower in grunt.

**Comment by AmirSavand** [comment]
If we can solve those 3 and we're all done.

**Comment by Alir3z4** [comment]
Does it compress and minfiy all the assets in one file ?
How does that gonna work ?

**Comment by Alir3z4** [comment]
Wait what ?
what a minutto!

So that will work if you just change it from bower to node_modules ?
If you add a new package via bower or remove bower.json completely would that make the list re-created or it will just wont change it ?

Because wiredep works via bower.json and it seems you're still using its syntax in index.html.

What other problems this one has ?

**Comment by AmirSavand** [comment]
I renamed the pattern in grunt, bower packages are still in but I use all npm.

No other issues.

**Comment by Alir3z4** [comment]
If it works let's get this merged.

**Comment by Alir3z4** [comment]
However, I see the build doesn't pass.

**Comment by Alir3z4** [comment]
Ok, I closed the browserify.
I'll continue on this

**Comment by AmirSavand** [comment]
If we get this work it's be so good.

Webpack and other stuff are good too but this pull is the fastest way and we're already on npm too.

**Comment by Alir3z4** [comment]
Amir, I don't think we can get this working.
There are modules that you can;t just import them from node_modules.
Because node_module stuff are SystemJS and some of them have `require()` in
them that need to be transpiled for browser use, therefor using them won't
work.

**Pull request closed without merging**
