### PR TITLE
Add Custom Domain for site settings

### LINKED ISSUE #416: Custom Domain for Site Settings
User should be able to set a custom domain for their site.
After setting a custom domain that is not a subdomain of GoNevis then user should be informed to use a CNAME or ALIAS to point their custom domain to the GoNevis blog.

The message is as follow:
```
Point a CNAME/ALIAS to `BLOG_URL.gonevis.com` via your domain registrar DNS manager.
```

### LINKED ISSUE #801: Fix edit icon position of site cover
image

Should be a bit lower.

### PR DESCRIPTION
**Pull request by ArsalanSavand**
Ability to add and remove custom domains for site, in site settings page.

#### Fixes

Fixes #416 
Fixes #801 

#### Design

image

image

image

image

image

### CODE REVIEW

**Comment by Alir3z4** [comment]
@AmirSavand I have this in mind for custom domain list

image


Domain name on the left is the one that user adds and on the right side is the user blog address like (alireza.gonevis.com)

The tooltip of the help icon:

image

**Comment by AmirSavand** [comment]
@Alir3z4 didn't finish the custom domain functionality, but checkout the settings page, did lots of work on it.

Request changes if needed.

**Comment by Alir3z4** [comment]
@AmirSavand I can't build it on heroku for review.
It seems package.json and its lock are in conflicts.

```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  >=0.10.0
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version >=0.10.0...
       Downloading and installing node 9.4.0...
       Using default npm version: 5.6.0
-----> Restoring cache
       Skipping cache restore (not-found)
-----> Building dependencies
       Installing node modules (package.json + package-lock)
       npm ERR! code EINTEGRITY
       npm ERR! sha1-bp1/hRSjRn+l6fgswVjs/B1ax28= integrity checksum failed when using sha1: wanted sha1-bp1/hRSjRn+l6fgswVjs/B1ax28= but got sha1-Ywo13+ApS8KB7a5v/F0yn8eYLcw=. (657458 bytes)
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /app/.npm/_logs/2018-01-20T06_46_09_550Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by AmirSavand** [comment]
@Alir3z4 Check the screenshot instead.

I also need the exact text to show the user when he adds a custom domain.

**Comment by AmirSavand** [comment]
@Alir3z4 I get `{"detail":"Method \"DELETE\" not allowed."}` how can I delete a custom domain?

**Comment by AmirSavand** [comment]
@Alir3z4 updated the screenshots, check em out.

**Comment by Alir3z4** [comment]
The screenshots looks really good.
I'll look into the error you're getting and get back to you.

**Comment by Alir3z4** [comment]
> @Alir3z4 I get {"detail":"Method \"DELETE\" not allowed."} how can I delete a custom domain?

it's `remove-custom-domain`

**Comment by Alir3z4** [comment]
image

should be like a confirm box and should not be closed until user clicks "OK".

**Comment by Alir3z4** [comment]
After domain has been set succesfully, the message should say as follow:

"Supply {BLOG_URL} to your DNS provider for the destination of CNAME or ALIAS records."

BLOG_URL=`blog-domain.gonevis.com` and it's not the custom domain

**Pull request merged**
