### PR TITLE
Tour

### LINKED ISSUE #450: Add tour system

### PR DESCRIPTION
**Pull request by AmirSavand**
Resolves #450 

```js
var steps = [new TourStep("#selector", "Title of step", "Content of step")];
var tour = new Tour("sample", steps);
```

### CODE REVIEW

**Comment by Alir3z4** [comment]
This is blocked for backend now.
backend needs to make a better data handling on this.
Once that's done, I'll let you know;

**Comment by Alir3z4** [comment]
@AmirSavand This is not blocked anymore.

New changes on the backend:

* Tour will be completely `Null` when all the fields are `True`.
* When Tour is null, the login will return `Null` as its value, so if it's null then it means there's no need to show any tour and user has completed the tour.

**Comment by AmirSavand** [comment]
Good.

**Comment by Alir3z4** [comment]
@AmirSavand this can go in, do you need anything else ?

**Comment by AmirSavand** [comment]
No, I need to all tours and add backend functions too.

**Comment by Alir3z4** [comment]
finally

**Pull request merged**
