### PR TITLE
Webpackios!

### LINKED ISSUE #868: Bower, Browserify, NPM, WebPack and AngularJS
Since you mentioned the issue with bootstrap and NPM etc.
I spent some hours trying to get the project using "npm" only for both node modules and web modules.
Using browserify or Webpack is our only chance to get the build working and move forward.

However since we heavily depend on Grunt and tools around especially changing environment and live-reload I couldn't easily find a solution for it.

I can say, it crossed my mind to just wipe everything and migrate to angular2.
The AngularJS EOL is 2021, which is a long time but I am not sure about other tools we're using. Not all of our stuff will follow such EOL.

### PR DESCRIPTION
**Pull request by Alir3z4**
Fixes #868 

- [x] Remove Grunt
- [x] Remove bower
- [x] Make webpack shine
- [x] Run tests
- [x] Coverage reporting
- [x] Different ENV for local, staging, production:  https://github.com/SavandBros/gonevis-dash/pull/871#issuecomment-394097601
- [x] Replace ng-includes with Angular Components https://github.com/SavandBros/gonevis-dash/pull/871#issuecomment-394114728

### CODE REVIEW

**Comment by AmirSavand** [comment]
Wow, so much stuff going on.

If this doesn't work, don't waste time on it, after feed on gonevis.com we'll make it angular 6.

For now (if webpack fails) we stick with npm + bower + grunt.

**Comment by AmirSavand** [comment]
Nice node update.

**Comment by Alir3z4** [comment]
@AmirSavand this is ready.
You can start working on it.

do a "npm install" and run it with "npm start" and you will see the application.
There are some errors that you can fix which I mentioned in the commits.

let me know if you get to any errors.

**Comment by AmirSavand** [comment]
Alright, cool.

**Comment by Alir3z4** [comment]
Also you still need to figure out the constants as well for dev, staging
and production.

**Comment by Alir3z4** [comment]
Yes, the reporting works now

**Comment by AmirSavand** [comment]
Update for this branch: https://github.com/SavandBros/gonevis-dash/pull/874

**Pull request merged**
