### PR TITLE
Write publish

### LINKED ISSUE #852: Add publish button to editor
And other improvements

### LINKED ISSUE #853: Canceling insert images removes all images (sometimes)

### LINKED ISSUE #854: Fix editor sidebar in dark mode

### PR DESCRIPTION
**Pull request by AmirSavand**
# Fixes

- Fixes #854 
- Fixes #853 
- Fixes #852 

# Screens

image

image

image

## Responsiveness

Browser with more than 1000px:

image

Browser with smaller than 1000px:

image

### CODE REVIEW

**Comment by Alir3z4** [comment]
way way!

**Comment by Alir3z4** [comment]
any screenshot ?

**Comment by AmirSavand** [comment]
Yes

**Comment by Alir3z4** [comment]
So would the duplicate buttons still exists in ?

image

**Comment by AmirSavand** [comment]
What do you want to remove?

**Comment by Alir3z4** [comment]
the buttons in the sidebar should be removed then ? right ?
since we have them in the header

**Comment by AmirSavand** [comment]
I think it's ok to keep them, because the publish button, publishes the post imminently but the toggle button only change the status.

We can however, remove the **View on site** button.

**Comment by Alir3z4** [comment]
yes, let's remove the view on site button in the sidebar

**Comment by Alir3z4** [comment]
the rest of stuff look really good

**Comment by AmirSavand** [comment]
Ok

**Comment by AmirSavand** [comment]
Approve

**Pull request merged**
