### PR TITLE
Remember last site

### LINKED ISSUE #910: Remember what blog I was working on
Currently dashboard doesn't remember which blog I was working in, so when I enter the dashboard it select one for me (_the latest ?_).

When opening the dashboard, I want to work on the same blog that I closed the dash, Either login or openning it after a while.

### PR DESCRIPTION
**Pull request by AmirSavand**
Resolves #910

### CODE REVIEW

**Comment by Alir3z4** [comment]
What if local storage or cookies are wiped out ?
If I visit from other browser or different computer?

**Comment by AmirSavand** [comment]
Well this is browser level of storage.

**Comment by Alir3z4** [comment]
What do you need from backend so we can have it world wide ?

On Jul 4, 2018 17:37, "Amir Savand" <notifications@github.com> wrote:

Well this is browser level of storage.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/SavandBros/gonevis-dash/pull/921#issuecomment-402497408>,
or mute the thread

**Comment by AmirSavand** [comment]
We can have this for now and implement backend settings later.

**Pull request merged**
