### PR TITLE
Upgrading to CircleCI version 2

### LINKED ISSUE #714: Upgrade CircleCI to use version 2

### LINKED ISSUE #879: Linting and Code Quality
This should be enforced on the build, tests and having a seperate npm script entry to run it.

### PR DESCRIPTION
**Pull request by Alir3z4**
Fixes #714 
Fixes #879

To run jshint on the code:

```bash
$ npm run code-quality
```

### CODE REVIEW

**Comment by AmirSavand** [comment]
Changelog?

**Comment by Alir3z4** [comment]
still working on it.
dealing with a weird issue

**Comment by AmirSavand** [comment]
Then add `in progress` and remove `needs review`. Use waffle please.

**Comment by Alir3z4** [comment]
Sorry, my bad.

**Comment by AmirSavand** [comment]
What's this:

```
ci/circleci: jshint — Your tests failed on CircleCI
```

Why `jshint` is considered tests? I suppose you're fixing it.

**Comment by Alir3z4** [comment]
JSHINT should be in the our CI flow as well.
It's not part of the tests but part of CI.

3 things happens:
* Build: To check that our code builds as normal
* Test:; Running tests.
* jshint: to check for code quality

Please note, each of these checks happen individually.

**Pull request merged**
