### PR TITLE
Add option to remove branding

### LINKED ISSUE #837: Option to remove GoNevis branding from the blogs
It's a true/false attr in Site Settings.
The key name is `remove_branding`.

### PR DESCRIPTION
**Pull request by AmirSavand**
Fixes #837 

image

### CODE REVIEW

**Comment by Alir3z4** [comment]
Make the help text to be like
Will remove GoNevis.com name, brand and logo.

**Comment by AmirSavand** [comment]
@Alir3z4 I removed the period since other labels don't have it.

**Comment by Alir3z4** [comment]
> @Alir3z4 I removed the period since other labels don't have it.

Actually all the sentences should have it

**Comment by AmirSavand** [comment]
Ok

**Pull request merged**
