### PR TITLE
Resolves: "Google AdSense to blog settings"

### LINKED ISSUE #1138: Add Google AdSense to blog settings
Available for professional plan only.

### PR DESCRIPTION
**Pull request by AmirSavand**
Closes #1138 

Depends on #1137

### CODE REVIEW

**Comment by Alir3z4** [comment]
@AmirSavand what's left on this ?

**Comment by AmirSavand** [comment]
Everything, this only contains changelog change :D

**Comment by AmirSavand** [comment]
Ready but not tested on staging (waiting back-end).

**Comment by Alir3z4** [comment]
@AmirSavand backend is deployed for staging so you should be able to test it there.
Let me know how it is on staging.

**Comment by AmirSavand** [comment]
@Alir3z4 `http://draft.gonevis.com/api/v1/website/site/5406c9a9-4ed8-4257-b383-3aa37d43d8e1/google-adsense/` is 404

**Pull request merged**
