### PR TITLE
Site cover edit icon position

### LINKED ISSUE #801: Fix edit icon position of site cover
image

Should be a bit lower.

### PR DESCRIPTION
**Pull request by Momjo**
Fixes #801

### CODE REVIEW

**Comment by Alir3z4** [comment]
Oh I very like, danke!

**Comment by Momjo** [comment]
bitteschön, with pleasure!!

**Comment by Momjo** [comment]
Aha ok, i didn't know that

**Comment by AmirSavand** [comment]
@Momjo thanks for the pull request, but the new design is already change din #416

**Pull request closed without merging**
