### PR TITLE
[WIP] Fixes #868: Browserfify

### LINKED ISSUE #868: Bower, Browserify, NPM, WebPack and AngularJS
Since you mentioned the issue with bootstrap and NPM etc.
I spent some hours trying to get the project using "npm" only for both node modules and web modules.
Using browserify or Webpack is our only chance to get the build working and move forward.

However since we heavily depend on Grunt and tools around especially changing environment and live-reload I couldn't easily find a solution for it.

I can say, it crossed my mind to just wipe everything and migrate to angular2.
The AngularJS EOL is 2021, which is a long time but I am not sure about other tools we're using. Not all of our stuff will follow such EOL.

### PR DESCRIPTION
**Pull request by Alir3z4**
Fixes #868

### CODE REVIEW

**Comment by AmirSavand** [comment]
Hmm, this is weird haha, we still have to try all npm first.

**Comment by AmirSavand** [comment]
You sure tests pass?

**Comment by Alir3z4** [comment]
This is hell on earth.
I'm going to close it!

**Comment by Alir3z4** [comment]
Although I'm so close to this.
The latest commit actually builds the whole thing successfully.
The only thing that is left is the ngtemplate cache

**Pull request closed without merging**
