### PR TITLE
Update to FontAwesome 5

### PR DESCRIPTION
**Pull request by ArsalanSavand**

### CODE REVIEW

**Comment by Alir3z4** [comment]
@AmirSavand @ArsalanSavand can you guys update and make it working so we can merge ?

**Comment by AmirSavand** [comment]
@Alir3z4 this is a different pull needs lots of work and visual testing.

We'll do this later

**Comment by Alir3z4** [comment]
Any ETA ?

**Comment by AmirSavand** [comment]
Since the webpack change, this pull request is no longer valid.

**Pull request closed without merging**
